<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.00">
  <DataList Id="2b2d4cce-6099-4867-a3d7-a9225a841be7" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/11826d48-eac9-4e0b-a3fa-d353d0757d55" PlcIdentifier="49232636-c7c0-4854-ad5e-4453b849e395" TargetAttributes="PlcNext,UserManagedComponentInstances,ResourceGlobalPorts" TargetVersion="0/2022.9.0" UICulture="en-US">
    <Datum Uuid="574bc578-b65f-4bcf-8500-303507148dd0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1e43779a-6294-4348-b875-59ba855c02e6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_PLC_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Higher level PLC in RUN</Comment>
        <DisplayName>PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_PLC_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_PLC_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9184d118-052d-473d-a5ed-e9b765756bc1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="30175a82-42a8-4438-a330-2320dac8b837" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Connection to Profinet-Controller</Comment>
        <DisplayName>PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="398a5078-eaa7-4b1d-a6d0-3ed015231c17">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="747e511f-c81a-441c-9c83-54b677ed27ab" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>IOP status of the higher-level control system</Comment>
        <DisplayName>PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_OUTPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="79e2294a-315f-4097-8f79-c2e9a9942ff0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e8b85915-d04d-4f25-96fb-e18005f4f65a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>IOC status of the higher-level control system</Comment>
        <DisplayName>PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_INPUT_STATUS_GOOD</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="be81711c-6796-4142-8630-06ee2e6e3001">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="85a1fb46-7497-45d0-81c0-fa52a26f9a77" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_DATA_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Process data length</Comment>
        <DisplayName>PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_DATA_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_DATA_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a58c044e-0196-4734-8dda-460c0685fc6f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e3b64a16-2809-47cf-ae1e-91e1c265a0f6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Output process data</Comment>
        <DisplayName>PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="03205368-ed16-4293-8d77-9f18db700e62">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="aafb8926-65fd-4c25-8f16-2ca6896be209" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_S1_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>PND_IO_512</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment>Input process data</Comment>
        <DisplayName>PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_S1_INPUTS</Label>
        <Access>I</Access>
        <DataType>Octetstring[512]</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_S1_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9664a23d-f062-4e2d-99df-a23f1f12bfd0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="10d61229-994c-458a-a6dd-26be7d299b1f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Usage>Global</Usage>
        <DataType>INT</DataType>
        <Address />
        <InitValue>INT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <Access>I</Access>
        <DataType>Signed16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PND_IO_DRIVEN_BY_PLC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="11c6afef-f106-4d9d-acca-732cb24e1eb1">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>~DI8</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / ~DI8</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="485fb48e-6405-4ff4-9ad8-19975d457f4e">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>~DO8</Label>
        <Access>Q</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / ~DO8</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="c97d99a3-b4f8-4dde-9dde-40ec0e77fefb">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=io0]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN00</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN00</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="541638d3-c694-4ba7-bbb3-54d2c02ebf64">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=io1]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN01</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN01</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="1d5fd25d-f493-4800-b5c7-f977fcc04d36">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=io2]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN02</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN02</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5e04eb5b-28b6-4149-9360-66fbcce1c11b">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=io3]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN03</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN03</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="8aa5a6e7-a8b2-401b-bb4d-e98bebc7d86d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=io4]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN04</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN04</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="acd9792b-dbad-4c65-9460-96d3ccd16f8d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=io5]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN05</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN05</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="ccdf3b30-60b9-42ac-ab64-19c7529084e5">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=io6]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN06</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN06</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="fe51e6e7-320e-44d4-a2b0-3e7962ba61ce">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=io7]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>IN07</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / IN07</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="df16731b-79fe-4928-9eea-f08d9d0b9c40">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=io8]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT00</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT00</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="fb395621-9fac-4c19-970c-2244b34a1318">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=io9]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT01</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT01</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="d6a11d81-290f-4439-b0f0-4a218834a83d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=io10]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT02</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT02</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="07bc721a-b871-408d-83b4-a5241d3c6e22">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=io11]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT03</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT03</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="bdc02b79-7d80-4af4-be2d-12777f631166">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=io12]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT04</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT04</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="c43d9a86-9b08-4b11-98e3-9eb8ea677787">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=io13]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT05</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT05</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="bdde3225-b44b-45e7-a2e0-7d34d4210356">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=io14]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT06</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT06</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="a04e201d-51aa-4e96-ade2-0dbcd5fadbbb">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=io15]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Label>OUT07</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-1 / OUT07</DisplayName>
        <NodeId>0</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>1</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="1fb13bb9-301c-4cc4-94f0-14cb374f341a">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>~DI8</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / ~DI8</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="dc3e21eb-84f8-4985-8c71-42b994f2b253">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>~DO8</Label>
        <Access>Q</Access>
        <DataType>Bitstring8</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / ~DO8</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="bd0acc66-3b8c-4e0b-9ee7-93411c189b55">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=io0]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN00</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN00</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="e34a25a5-50b4-4331-a983-eebf6036b1ec">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=io1]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN01</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN01</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="1b9dca91-608f-4ef9-b9d7-130b052bae15">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=io2]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN02</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN02</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="e4c7c9d4-e5df-4406-ac52-70fa175742b7">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=io3]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN03</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN03</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="10d6bf8d-ede5-4256-a826-e18dd020a421">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=io4]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN04</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN04</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="bfea2d3d-362a-48e6-8042-38264318f9be">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=io5]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN05</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN05</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="d95f134d-ebe4-4801-a7bf-e24560e863d9">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=io6]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN06</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN06</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="8b624b9f-d352-4432-b40a-812cd2d0b4a6">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=io7]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>IN07</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / IN07</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="7038ea4f-9a90-4305-86c2-8eb2180fb65b">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=io8]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT00</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT00</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="0aa0f1ef-4ea7-4df8-95a8-5104b65cea31">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=io9]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT01</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.1</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT01</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="179c8d53-dcbb-443f-bf5a-789f6cffac95">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=io10]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT02</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.2</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT02</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="0097df36-1c19-4507-bcf6-44375233598d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=io11]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT03</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.3</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT03</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="38b6a688-fe92-40f0-8b4c-d081e99f2c58">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=io12]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT04</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.4</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT04</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5cf19087-ea50-4cb0-ae26-03185a13a60b">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=io13]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT05</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.5</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT05</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="78eb27d9-5b8a-436d-800a-ae5a78eaa70d">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=io14]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT06</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.6</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT06</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="c637fa01-29e1-4e5b-b0dd-0b6b36b75d06">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=io15]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Label>OUT07</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>1.7</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>dio-2 / OUT07</DisplayName>
        <NodeId>1</NodeId>
        <InputFrameId>0</InputFrameId>
        <OutputFrameId>0</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="45c51175-a60c-4f38-826f-65722a3372bb">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>~OUT64</Label>
        <Access>Q</Access>
        <DataType>Octetstring[8]</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / ~OUT64</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="dc9e8d11-547d-4be2-9807-68d047cadc60">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=o_0_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 1, pulse duty factor</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 1, pulse duty factor</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="6e14008d-9216-476d-bb53-4314ffa2a77b">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=o_0_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 1, push-pull output</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>0.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 1, push-pull output</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="e92826b7-54b4-42c6-89f7-2a27f6578a33">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=o_2_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 1, number of pulses</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>2.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 1, number of pulses</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="9be37474-ff93-4183-9047-bb41a8a3b77f">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=o_2_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 1, frequency</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>2.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 1, frequency</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="a8b4fd7b-4a78-4c0f-ae48-430a0e384cf9">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=o_4_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 2, pulse duty factor</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>4.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 2, pulse duty factor</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="2b1fd887-ad41-449d-a03f-66d13f6e2ecd">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=o_4_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 2, push-pull output</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset>4.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 2, push-pull output</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="f1a57324-594f-4020-8ee4-dc1287677dfa">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=o_6_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 2, number of pulses</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>6.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 2, number of pulses</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5d1295f1-a5a4-4959-8de4-404f05406b8a">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=o_6_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Label>Channel 2, frequency</Label>
        <Access>Q</Access>
        <DataType>Unsigned16</DataType>
        <Offset>6.0</Offset>
        <IsSafe>False</IsSafe>
        <DisplayName>pwm-1 / Channel 2, frequency</DisplayName>
        <NodeId>2</NodeId>
        <InputFrameId>2</InputFrameId>
        <OutputFrameId>3</OutputFrameId>
      </Role>
    </Datum>
    <Datum Uuid="5489664a-f329-452d-adde-816b07983405">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d86f6307-b597-45fe-9c63-8912ae491be5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4ebd618a-9b1d-4c73-9aa8-79694c87b702">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="90afddd4-4234-4981-8d1c-7d36856f1150" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="506adf71-48f4-47f7-b1a1-4273407cbb6a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b2f6a09a-d3a0-474b-a54f-476ec5547213" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f209f984-dedb-47ef-8c77-23b9bd43fd20">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="18a4ba4e-c25a-4006-a33e-8bedacd5c83d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c9885b60-27b2-4315-bdea-830dba29689c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="02eed32e-2c27-4634-ace9-84c22454522e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="92a87e31-f3ad-4f7c-9dc6-284a64765240">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4e77a90b-d4e1-42d3-9107-0136bef48dab" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6583d8e7-a959-42f1-8fc7-685391311ec4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="297a93fb-38b2-41b5-84fa-24188c52d404" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a7d5f9df-a193-4cc6-898b-568b2a332295">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9922d81c-d1d5-48b6-8e7a-1fcbe7bee5d7" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="427d124f-a8db-452e-aafc-d5aa51e47b23">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8b5ca678-b646-423b-a872-b965abc13cdc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3f0a5bbb-ad2a-4b90-aaa5-caae9670ba9b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ee595bc3-3cbf-497e-a82a-688711fe6926" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c61808dc-060c-4184-93df-7edb34edf0f3">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="31991f4a-9cdc-4844-93a2-c6f555646609" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d82bdf70-21d5-4a21-8ace-6af3451fffc9">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ce7005a9-c7eb-4272-9e9d-4c6f21ea535e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fb5f093d-1a32-495d-a692-0cbc046b2a83">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cf1a4835-6645-4fc7-a351-6e9fe5843c6b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Axioline F / AXIO_DIAG_STATUS_REG_PW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bdebc8b4-2799-43e8-9be9-8d5b1a8549fb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cda754ad-2407-42f2-b84e-a6774dff9770" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ede3c6da-5f71-437e-9e1b-532fa5e1052a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ffb0dce0-f863-4d8f-9e27-54d17627c1ec" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0bf184bf-ab5a-421a-872e-18b6726fd8b7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4d34df47-eb7c-426f-a176-f46416300e80" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_SYSFAIL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="aadb738e-6001-45c6-88b2-19d3fe4284a8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7124133f-d297-438c-81e9-1913fb02c341" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_WARN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5ec53cb4-58e3-406b-926d-98aecb5e0917">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0eacd93a-5734-4de8-93f2-6b86fcfe5053" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_QUAL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c5ad27d3-e88d-43d1-87ef-124ed82013cf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ce4bbcad-7a30-4bad-955f-14728fad880a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_USER</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="906b9ef7-7f60-49f1-bfda-6d7cb93c0f17">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f925fdae-19ed-4d4f-b6c2-bf282f873422" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_PF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="66be68b7-50f0-4450-af96-c17109fccbbb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ca11a272-c085-4f57-8c73-c459f2616abb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_BUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4da01e6e-7e1b-44d7-b721-c5821f87a0db">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0e6316f9-830a-4e25-ba68-f5202f584581" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_CTRL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4823fa4e-576a-43ac-93de-9b2d8d2f76a7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="51789e77-36b3-4134-af93-4872b4fa88ee" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_DTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="75c51af1-71c9-4711-acfc-c8237a041e09">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fac7976f-b0a1-4e13-903a-1db64b6cb294" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="3f648b08-06f8-4fd9-bbc6-b12cf50d886c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="50aac831-d992-4c94-bb7f-51e2c0d86219" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_ACT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2c63b26a-beb4-4bbf-b872-0644f5ece168">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e35f4257-9c5f-4e02-932c-843bd325f5c4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_STATUS_REG_RDY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="77a20615-37b7-4c48-86f7-00a9bbf82b37">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="329f9354-c495-4b03-b865-71c4861ef45f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="0d7863cb-8ad3-4f5f-b027-f7a59c9bf50b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a1389850-b15f-499e-9c97-852660bc1475" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="125307f2-3d7c-4222-ab96-ed04c3036ee7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fad70604-3add-49c7-9bcb-eb8b8de13681" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_HI</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="651d7fe2-0fcc-410e-9c4e-2d7c93e26a88">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="54060544-4066-430a-a2a0-1e94e77da916" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Usage>Global</Usage>
        <DataType>BYTE</DataType>
        <Address />
        <InitValue>BYTE#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <Access>I</Access>
        <DataType>Bitstring8</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>AXC F IL ADAPT / AXC XT IB / IB_DIAG_PARAM_2_REG_LOW</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="321ef04d-67d7-4649-8254-2ac9566d7fc6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b6c15018-2791-431d-8c25-e2e8c0912eca" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>ESM_DATA</Name>
        <Usage>Global</Usage>
        <DataType>ESM_DAT</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_1">
        <Label>ESM_DATA</Label>
        <Access>I</Access>
        <DataType>ESM_DAT</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / ESM_DATA</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="058a1b55-1669-460e-aff6-6a58a17c8c90">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="808ee767-72d7-4660-b4e2-57b6f52a0e1b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>RTC</Name>
        <Usage>Global</Usage>
        <DataType>RTC_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_1">
        <Label>RTC</Label>
        <Access>I</Access>
        <DataType>RTC_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / RTC</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="df9e83e7-7eb1-4cf3-a6f6-101257fc2324">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4387efbd-2eaa-48ad-b73c-431bdaf3d710" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>DEVICE_STATE</Name>
        <Usage>Global</Usage>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_1">
        <Label>DEVICE_STATE</Label>
        <Access>I</Access>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / DEVICE_STATE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ec07011f-7bb9-46d1-8996-5a8d7f5b53ed">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="288aca7a-d7bc-46dc-8009-114ce56f43d0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>USER_PARTITION</Name>
        <Usage>Global</Usage>
        <DataType>PARTITION_INFO</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pddi4]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_1">
        <Label>USER_PARTITION</Label>
        <Access>I</Access>
        <DataType>PARTITION_INFO</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>PLCnext / USER_PARTITION</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4852b5a5-96f9-4609-86e8-1b30dc7d7205">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b099e325-68be-4c56-9d8e-64e00bd49580" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_SYSTEM_BF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_SYSTEM_BF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_SYSTEM_BF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="67d5053f-c05e-4668-a0ab-3fb31819dce2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="98e45f04-4970-4a1e-bd95-51c30254f858" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_SYSTEM_SF</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_SYSTEM_SF</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_SYSTEM_SF</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="36989ab3-c056-4ee1-b4f9-7a4312042b30">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4ceca544-fc55-4212-ae0e-da2ecb185ab0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_MAINTENANCE_DEMANDED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1bcab274-99d6-4b98-9f15-82fa9a424fcb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="28730076-558d-4fe6-ad71-a762b697eb98" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_MAINTENANCE_REQUIRED</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4a6cb264-5a62-4ab9-acbb-aced70b025a5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1ca6a0ef-0e3f-48bb-8434-1bb2b7d87683" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_CONFIG_STATUS</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_CONFIG_STATUS</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b7344c08-8339-4f20-b59c-9de4e2029cf7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ed7eecaf-ccec-46a4-8dd7-078516cb0134" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_ACTIVE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7f6a001c-74ad-4f96-98c0-b24079e7077c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f289e92b-42fe-4aba-839e-990759af11b9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_READY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="f610857c-547c-4f9d-bf5f-b42c1a10f45a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a2af5b48-f032-4e79-b0d7-5df73c1d6622" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <Access>I</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_CONFIG_STATUS_CFG_FAULT</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a4ca68db-a6eb-4963-bc47-cd5a32b21b61">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="30f73f98-48ad-4e2c-8ac4-95f5f9887c44" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_FORCE_FAILSAFE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d89cba2a-3e31-4cbb-ae8f-939d39c05842">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="e8d3ccd3-ae1e-4aae-923c-3599482d7a9a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PNIO_FORCE_PRIMARY</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=pncpd10]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_4">
        <Label>PNIO_FORCE_PRIMARY</Label>
        <Access>Q</Access>
        <DataType>BOOL</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Profinet / PNIO_FORCE_PRIMARY</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="30772793-a9cd-440a-b041-2f43dfb8d632">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c8a1a1ed-91c6-4a5b-a16d-22efd2186a65" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30000</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>IP_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="01f68b29-31db-4dc0-a389-b55a66f8aaa4">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2bed7fbe-9167-4c16-aec1-669d5479aebc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Usage>Global</Usage>
        <DataType>UINT</DataType>
        <Address>%MW1.30100</Address>
        <InitValue>UINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>TLS_ACTIVE_SOCKETS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7291a838-6828-4b5b-b212-8e178d229cf5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="96f490e3-61e2-4993-a306-b53d804a18b8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>HMI_STATUS2</Name>
        <Usage>Global</Usage>
        <DataType>HMI_STATUS_TYPE2</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>HMI_STATUS2</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_3">
        <Label>HMI_STATUS2</Label>
        <Access>I</Access>
        <DataType>HMI_STATUS_TYPE2</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>HMI Web Server / HMI_STATUS2</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4f37275b-59de-4a32-aff3-e300f869f4d0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a520eba5-5cf1-4e78-b9ef-dde4f4693e71" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>HMI_CONTROL</Name>
        <Usage>Global</Usage>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_3">
        <Label>HMI_CONTROL</Label>
        <Access>Q</Access>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>HMI Web Server / HMI_CONTROL</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="89a807e9-0798-4f1f-b0d0-34a5731c2ce8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cdec45a6-eb58-4ab8-b80e-2296ea8816af" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_INPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_INPUTS</Label>
        <Access>I</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="94fe3987-125b-47ee-a66a-ac3b34b8c427">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f981b7f0-0854-4ef9-aa7c-0572bcf134c7" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_OUTPUTS</Name>
        <Usage>Global</Usage>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Address />
        <InitValue />
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_OUTPUTS</Label>
        <Access>Q</Access>
        <DataType>EIPD_IO_ARRAY</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="657161d7-cd36-4c48-9df0-bac63920da71">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8cdffc69-6c60-4499-83b3-640b81e07757" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_VALID_DATA_CYCLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9336fd5c-a5d1-42be-af50-7b8403e4fdc6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="984c0d53-5e88-426f-a495-625d08c1e825" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_PEER_IDLE</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_PEER_IDLE</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_IDLE</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fec61152-4f3f-483a-a736-ae44a08d3d93">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="752e82b5-bf6a-4d49-bbfe-c24c27bab3d0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_PEER_RUN</Name>
        <Usage>Global</Usage>
        <DataType>BOOL</DataType>
        <Address />
        <InitValue>FALSE</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_PEER_RUN</Label>
        <Access>I</Access>
        <DataType>Boolean</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_PEER_RUN</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9d4b0225-2b75-494f-b3fd-f08eca96d50c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="0f41d00f-03f2-4d6c-b7c4-c7cc0083c7e4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_OUTPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5d15a433-77e1-4713-8d11-ae1426e69ded">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f4c2e216-f55d-4391-8d71-c63c3b4f48ab" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Usage>Global</Usage>
        <DataType>WORD</DataType>
        <Address />
        <InitValue>WORD#16#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_7">
        <Label>EIPD_INPUTS_LENGTH</Label>
        <Access>I</Access>
        <DataType>Bitstring16</DataType>
        <Offset />
        <IsSafe>False</IsSafe>
        <DisplayName>Ethernet/IP / EIPD_INPUTS_LENGTH</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="708180fe-66f2-4bf2-89b1-cdc9f99ab686">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8056f3aa-483d-4802-8600-57ca3b36e1b8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915">
        <Name>PLC_CRC_PRJ</Name>
        <Usage>Global</Usage>
        <DataType>ULINT</DataType>
        <Address>%ML1.10000</Address>
        <InitValue>ULINT#0</InitValue>
        <IsRetain>False</IsRetain>
        <IsConstant>False</IsConstant>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <Comment />
        <DisplayName>PLC_CRC_PRJ</DisplayName>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="47347734-6233-4147-9178-44a1a6182a4e">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>~DO8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / ~DO8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1f371912-e8d2-40b5-85c2-b703f69ebc2e">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io8]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT00</DisplayName>
      </Role>
      <Role TypeName="OutPort" ObjectId="b6bc2df3-7b74-440c-bd6f-e45073683e03" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_StepperFWD</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_StepperFWD</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="95eba192-799c-40fa-b248-0a16ff58513d">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io9]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT01</DisplayName>
      </Role>
      <Role TypeName="OutPort" ObjectId="cffe2b48-116a-48b8-bf9a-77987009f511" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_StepperBWD</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_StepperBWD</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="5e63c090-98b3-4e85-9d00-6fdbda0d6768">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io10]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT02</DisplayName>
      </Role>
      <Role TypeName="OutPort" ObjectId="65d11424-6a13-4d35-bdd7-1d978646930d" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_PickUpRoutineDone</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_PickUpRoutineDone</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="af08a5ac-7d1e-42b4-8cd2-b7f5e56a4f29">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io11]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="e9666e95-a992-46e3-99bc-a88b5a357557">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io12]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="27375128-e607-45f0-9f33-494bc2dd48b5">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io13]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="ce36c5de-6530-4022-be25-249dacabd3cb">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io14]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="26d56b37-5794-4168-b0ab-7f071d2824fe">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io15]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>OUT07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / OUT07</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="4581dc1e-4148-4eb9-bfc5-a069360866be">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>~DI8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / ~DI8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="14bf83e6-bf6c-4b0c-beb6-7fa96173147f">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io0]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN00</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="b5087a9e-2b1e-48a1-81d5-a83e87141736">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io1]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="7fe9d98e-d7d2-4ffd-bc97-5dd50234a084">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io2]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="ab588ed4-22a8-42de-962b-3998c24fff8a">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io3]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="6c3d3f60-3960-4f5e-a6c3-006e1e143b03">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io4]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="9ecb42c8-a88e-4dce-8cfb-6fef21503339">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io5]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="349eb2a7-2219-4a9f-b3e5-290a603c9ff7">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io6]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="77157c58-b195-4f96-a6da-bddd9bfc293f">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io7]" SourceId="3d0365af-5f51-4def-b62a-c135f79c87f8">
        <Name>IN07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>0</NodeId>
        <DisplayName>dio-1 / IN07</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="414268fb-000d-49a3-a7d6-99504e43118d">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>~DO8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / ~DO8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="340fea80-d69d-4cf6-926c-5ebd8a94810a">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io8]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT00</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="527bc8bc-de9b-4795-b578-23256bf49b0c">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io9]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="9c68e92c-c93a-4396-8721-0d02c226fb9a">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io10]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f5926590-0d91-4a21-ad79-b894c60bfb19">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io11]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="5b094124-fa79-464c-8851-dd1653139f00">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io12]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="227a97bd-5c89-424e-9cb2-b780ace093ef">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io13]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="35d8f528-5cbd-4157-90fc-4d5b73fe7951">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io14]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="33a52831-82d1-469a-aba1-a677eeebad73">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=io15]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>OUT07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / OUT07</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="3868ef6f-d03f-4544-bd9e-883d7220e67e">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>~DI8</Name>
        <DataType>Bitstring8</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Bitstring8</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / ~DI8</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="5e8ba770-d806-4c0a-a0ab-69f2e2ac5cc1">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io0]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN00</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.0</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN00</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="2880430a-623b-4fcc-bc64-98c8b6fe027f">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io1]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN01</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.1</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN01</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="a1a459d6-2cda-43c4-ae8c-b0cb6323ae65">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io2]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN02</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.2</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN02</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="df22e3bc-a4be-4867-9801-4281fc4e092d">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io3]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN03</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.3</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN03</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="c0a8371d-6922-4a41-b128-1586b35af032">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io4]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN04</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.4</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN04</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="c21314d5-81f9-451b-8f07-298b4abb794f">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io5]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN05</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.5</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN05</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="910a243a-3be7-4d8e-8f91-a91d31bbc946">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io6]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN06</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.6</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN06</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="bc071245-60c2-4586-8953-ee7bfe08d4a8">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=io7]" SourceId="df768e97-0738-4fbc-85b9-ed7291239a13">
        <Name>IN07</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>1.7</Offset>
        <NodeId>1</NodeId>
        <DisplayName>dio-2 / IN07</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="fe3f5258-30ed-4668-89d9-59142874f48d">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="a132afdf-7d4a-4694-8887-666ced1c14f5" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_PickupRoutineStart</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_PickupRoutineStart</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="059db786-133b-4a6c-8d9d-6b5f2ae70537">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="78d82cd3-8bec-4c09-bee8-a4a0bddc827c" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_EndStopFWD</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_EndStopFWD</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="a0937ca3-60e2-4303-95e7-066d162cc592">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="c2e47920-08ad-441b-b4bd-ffc099c79925" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_EndStopBWD</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_EndStopBWD</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f3d01b61-d8b7-473a-9373-624f40d537e6">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="61e66f29-1843-41ca-a825-bd3ca302546b" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_PlateDetection</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_PlateDetection</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="bf0dec7b-b863-4888-891e-5cfddccfb511">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="f7f36768-27e0-4796-89b2-ba5d87e25f23" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_EndStopDown</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_EndStopDown</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="abc5225d-b4b0-4cfc-a044-37368afb8af4">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="73dba032-c7e7-4490-9093-c2f74e27b38c" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_EndStopUp</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_EndStopUp</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1a1d1927-6bf9-4293-b6b3-8bb1ecc33419">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="c7774938-567b-4759-9f48-8559d0d04e8e" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_StepperUp</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_StepperUp</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="424dedb5-d1c2-4ef8-b0a6-8954a4ba8513">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="c11696e9-c8cb-4acc-b88f-b88da3efb902" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_StepperDown</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_StepperDown</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="788412ce-bf35-445f-b28d-a694f0f516b5">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="2807c483-b708-4da3-977f-956a7355e9b0" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_DropOffRoutineStart</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_DropOffRoutineStart</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="1e8dfde3-a7f4-485e-bd86-89503741bac5">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="95263404-ab35-456b-be56-7aa0946569d7" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>q_DropOffRoutineDone</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : q_DropOffRoutineDone</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="11084519-fe91-4661-abca-461389d731e3">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="40f89350-698a-4a3f-b9b6-784c7d8a6305" SourceId="49232636-c7c0-4854-ad5e-4453b849e395.L7_2">
        <Name>i_EndStopFWDShort</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <ProgramInstance>MainInstance</ProgramInstance>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <DisplayName>Arp.Plc.Eclr / MainInstance : i_EndStopFWDShort</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="20a4143c-ff99-43f0-aa17-2a300a97b71d">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=iodpdout]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>~OUT64</Name>
        <DataType>Octetstring[8]</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Octetstring[8]</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / ~OUT64</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="90ce01c0-e1fd-4e9b-9a15-d60e60178f6a">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_0_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 1, pulse duty factor</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 1, pulse duty factor</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="6cbbd79b-65cf-41de-8851-97b77370c9f8">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_0_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 1, push-pull output</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>0.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 1, push-pull output</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f93f41e5-9a7a-455f-8a52-80ea0d4f9ba3">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_2_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 1, number of pulses</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>2.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 1, number of pulses</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="3269a8d8-b85a-4ca2-b843-994952d9e026">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_2_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 1, frequency</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>2.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 1, frequency</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="4bfa59a3-bb81-469a-a79c-9bea44b1295d">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_4_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 2, pulse duty factor</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>4.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 2, pulse duty factor</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="e8af64df-b50d-4185-996b-0514ec0c0347">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_4_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 2, push-pull output</Name>
        <DataType>BOOL</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>BOOL</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>4.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 2, push-pull output</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="f2f8d823-f31a-4bfa-8c12-b8269d3b0880">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_6_0a]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 2, number of pulses</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>6.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 2, number of pulses</DisplayName>
      </Role>
    </Datum>
    <Datum Uuid="eae9daee-5c9e-4afd-ba1b-84105ac989b5">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=o_6_0b]" SourceId="477c0859-12bc-4d48-9de5-5d346f747998">
        <Name>Channel 2, frequency</Name>
        <DataType>Unsigned16</DataType>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <PortDataType>Unsigned16</PortDataType>
        <PortMultiplicity>1</PortMultiplicity>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsHmi>False</IsHmi>
        <IsProficloud>False</IsProficloud>
        <IsRedundant>False</IsRedundant>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <Program>Arp.Io.AxlC</Program>
        <Offset>6.0</Offset>
        <NodeId>2</NodeId>
        <DisplayName>pwm-1 / Channel 2, frequency</DisplayName>
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False" />
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/e3bca5dc-ceef-4dc3-9cad-e9f38d18b915" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>574bc578-b65f-4bcf-8500-303507148dd0</RoleDatumUuid>
        <RoleDatumUuid>9184d118-052d-473d-a5ed-e9b765756bc1</RoleDatumUuid>
        <RoleDatumUuid>398a5078-eaa7-4b1d-a6d0-3ed015231c17</RoleDatumUuid>
        <RoleDatumUuid>79e2294a-315f-4097-8f79-c2e9a9942ff0</RoleDatumUuid>
        <RoleDatumUuid>be81711c-6796-4142-8630-06ee2e6e3001</RoleDatumUuid>
        <RoleDatumUuid>a58c044e-0196-4734-8dda-460c0685fc6f</RoleDatumUuid>
        <RoleDatumUuid>03205368-ed16-4293-8d77-9f18db700e62</RoleDatumUuid>
        <RoleDatumUuid>9664a23d-f062-4e2d-99df-a23f1f12bfd0</RoleDatumUuid>
        <RoleDatumUuid>5489664a-f329-452d-adde-816b07983405</RoleDatumUuid>
        <RoleDatumUuid>4ebd618a-9b1d-4c73-9aa8-79694c87b702</RoleDatumUuid>
        <RoleDatumUuid>506adf71-48f4-47f7-b1a1-4273407cbb6a</RoleDatumUuid>
        <RoleDatumUuid>f209f984-dedb-47ef-8c77-23b9bd43fd20</RoleDatumUuid>
        <RoleDatumUuid>c9885b60-27b2-4315-bdea-830dba29689c</RoleDatumUuid>
        <RoleDatumUuid>92a87e31-f3ad-4f7c-9dc6-284a64765240</RoleDatumUuid>
        <RoleDatumUuid>6583d8e7-a959-42f1-8fc7-685391311ec4</RoleDatumUuid>
        <RoleDatumUuid>a7d5f9df-a193-4cc6-898b-568b2a332295</RoleDatumUuid>
        <RoleDatumUuid>427d124f-a8db-452e-aafc-d5aa51e47b23</RoleDatumUuid>
        <RoleDatumUuid>3f0a5bbb-ad2a-4b90-aaa5-caae9670ba9b</RoleDatumUuid>
        <RoleDatumUuid>c61808dc-060c-4184-93df-7edb34edf0f3</RoleDatumUuid>
        <RoleDatumUuid>d82bdf70-21d5-4a21-8ace-6af3451fffc9</RoleDatumUuid>
        <RoleDatumUuid>fb5f093d-1a32-495d-a692-0cbc046b2a83</RoleDatumUuid>
        <RoleDatumUuid>bdebc8b4-2799-43e8-9be9-8d5b1a8549fb</RoleDatumUuid>
        <RoleDatumUuid>ede3c6da-5f71-437e-9e1b-532fa5e1052a</RoleDatumUuid>
        <RoleDatumUuid>0bf184bf-ab5a-421a-872e-18b6726fd8b7</RoleDatumUuid>
        <RoleDatumUuid>aadb738e-6001-45c6-88b2-19d3fe4284a8</RoleDatumUuid>
        <RoleDatumUuid>5ec53cb4-58e3-406b-926d-98aecb5e0917</RoleDatumUuid>
        <RoleDatumUuid>c5ad27d3-e88d-43d1-87ef-124ed82013cf</RoleDatumUuid>
        <RoleDatumUuid>906b9ef7-7f60-49f1-bfda-6d7cb93c0f17</RoleDatumUuid>
        <RoleDatumUuid>66be68b7-50f0-4450-af96-c17109fccbbb</RoleDatumUuid>
        <RoleDatumUuid>4da01e6e-7e1b-44d7-b721-c5821f87a0db</RoleDatumUuid>
        <RoleDatumUuid>4823fa4e-576a-43ac-93de-9b2d8d2f76a7</RoleDatumUuid>
        <RoleDatumUuid>75c51af1-71c9-4711-acfc-c8237a041e09</RoleDatumUuid>
        <RoleDatumUuid>3f648b08-06f8-4fd9-bbc6-b12cf50d886c</RoleDatumUuid>
        <RoleDatumUuid>2c63b26a-beb4-4bbf-b872-0644f5ece168</RoleDatumUuid>
        <RoleDatumUuid>77a20615-37b7-4c48-86f7-00a9bbf82b37</RoleDatumUuid>
        <RoleDatumUuid>0d7863cb-8ad3-4f5f-b027-f7a59c9bf50b</RoleDatumUuid>
        <RoleDatumUuid>125307f2-3d7c-4222-ab96-ed04c3036ee7</RoleDatumUuid>
        <RoleDatumUuid>651d7fe2-0fcc-410e-9c4e-2d7c93e26a88</RoleDatumUuid>
        <RoleDatumUuid>321ef04d-67d7-4649-8254-2ac9566d7fc6</RoleDatumUuid>
        <RoleDatumUuid>058a1b55-1669-460e-aff6-6a58a17c8c90</RoleDatumUuid>
        <RoleDatumUuid>df9e83e7-7eb1-4cf3-a6f6-101257fc2324</RoleDatumUuid>
        <RoleDatumUuid>ec07011f-7bb9-46d1-8996-5a8d7f5b53ed</RoleDatumUuid>
        <RoleDatumUuid>4852b5a5-96f9-4609-86e8-1b30dc7d7205</RoleDatumUuid>
        <RoleDatumUuid>67d5053f-c05e-4668-a0ab-3fb31819dce2</RoleDatumUuid>
        <RoleDatumUuid>36989ab3-c056-4ee1-b4f9-7a4312042b30</RoleDatumUuid>
        <RoleDatumUuid>1bcab274-99d6-4b98-9f15-82fa9a424fcb</RoleDatumUuid>
        <RoleDatumUuid>4a6cb264-5a62-4ab9-acbb-aced70b025a5</RoleDatumUuid>
        <RoleDatumUuid>b7344c08-8339-4f20-b59c-9de4e2029cf7</RoleDatumUuid>
        <RoleDatumUuid>7f6a001c-74ad-4f96-98c0-b24079e7077c</RoleDatumUuid>
        <RoleDatumUuid>f610857c-547c-4f9d-bf5f-b42c1a10f45a</RoleDatumUuid>
        <RoleDatumUuid>a4ca68db-a6eb-4963-bc47-cd5a32b21b61</RoleDatumUuid>
        <RoleDatumUuid>d89cba2a-3e31-4cbb-ae8f-939d39c05842</RoleDatumUuid>
        <RoleDatumUuid>30772793-a9cd-440a-b041-2f43dfb8d632</RoleDatumUuid>
        <RoleDatumUuid>01f68b29-31db-4dc0-a389-b55a66f8aaa4</RoleDatumUuid>
        <RoleDatumUuid>7291a838-6828-4b5b-b212-8e178d229cf5</RoleDatumUuid>
        <RoleDatumUuid>4f37275b-59de-4a32-aff3-e300f869f4d0</RoleDatumUuid>
        <RoleDatumUuid>89a807e9-0798-4f1f-b0d0-34a5731c2ce8</RoleDatumUuid>
        <RoleDatumUuid>94fe3987-125b-47ee-a66a-ac3b34b8c427</RoleDatumUuid>
        <RoleDatumUuid>657161d7-cd36-4c48-9df0-bac63920da71</RoleDatumUuid>
        <RoleDatumUuid>9336fd5c-a5d1-42be-af50-7b8403e4fdc6</RoleDatumUuid>
        <RoleDatumUuid>fec61152-4f3f-483a-a736-ae44a08d3d93</RoleDatumUuid>
        <RoleDatumUuid>9d4b0225-2b75-494f-b3fd-f08eca96d50c</RoleDatumUuid>
        <RoleDatumUuid>5d15a433-77e1-4713-8d11-ae1426e69ded</RoleDatumUuid>
        <RoleDatumUuid>708180fe-66f2-4bf2-89b1-cdc9f99ab686</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>